# Generated by Django 5.0.6 on 2024-06-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Jobseeker')], max_length=100, null=True),
        ),
    ]
