# Generated by Django 5.0.6 on 2024-06-18 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal_App', '0002_alter_custom_user_model_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('skills', models.TextField(null=True)),
                ('resume', models.FileField(null=True, upload_to='media/applyresume')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('applied_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_portal_App.add_job_model')),
            ],
        ),
    ]
